// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";

/// @dev CRITICAL cross-language test vector (SPEC §10 Step 9a item 1): `tools/` (viem's
///      `encodeAbiParameters` + `keccak256`) and this contract (Solidity's `abi.encode` +
///      `keccak256`, the exact expression `Tender.commit`/`revealPrice` use, SPEC §5) must
///      agree bit-for-bit on the price commitment formula. A mismatch here would mean a
///      bidder's own receipt tool produces a commitment their real on-chain `revealPrice`
///      call can never open -- silently costing them their deposit (their bid would sit
///      Eligible-but-never-opened until it collapses to F2 forfeiture).
///
///      The fixture is generated by `npm run gen:vector` (tools/src/genCommitmentVector.ts)
///      and checked into the repo, so `forge test` never depends on Node being installed.
///      Re-run both after changing anything about the commitment formula.
contract CommitmentVectorTest is Test {
    string internal constant FIXTURE_PATH = "tools/fixtures/commitment-vector.json";

    function test_CrossLanguage_CommitmentVector_MatchesTypeScript() public {
        string memory json = vm.readFile(FIXTURE_PATH);

        uint256 chainId = vm.parseJsonUint(json, ".chainId");
        address tender = vm.parseJsonAddress(json, ".tender");
        address bidder = vm.parseJsonAddress(json, ".bidder");
        uint256 price = vm.parseJsonUint(json, ".price");
        bytes32 docHash = vm.parseJsonBytes32(json, ".docHash");
        bytes32 salt = vm.parseJsonBytes32(json, ".salt");
        bytes32 expectedCommitment = vm.parseJsonBytes32(json, ".commitment");

        // Use the fixture's own chainId, not whatever this test happens to run under, so
        // this genuinely exercises `block.chainid` the same way the TS side used its
        // fixed `chainId` input -- not a coincidental match.
        vm.chainId(chainId);

        // The exact expression from Tender.sol's commit()/revealPrice() (SPEC §5):
        // keccak256(abi.encode(block.chainid, address(this), bidder, price, docHash, salt)).
        bytes32 commitment =
            keccak256(abi.encode(block.chainid, tender, bidder, price, docHash, salt));

        assertEq(commitment, expectedCommitment, "Solidity commitment != TypeScript commitment");
    }
}
