#!/usr/bin/env node
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getAddress, keccak256, toHex, type Hex } from "viem";
import { computeCommitment } from "./crypto/commitment.js";

/** Deterministically derives a valid, correctly-checksummed dummy address from a label. */
function dummyAddress(label: string) {
  return getAddress(keccak256(toHex(label)).slice(0, 42));
}

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * CRITICAL cross-language test vector (SPEC §10 Step 9a item 1): fixed, reproducible
 * inputs, the commitment this TS tool computes for them, written to a JSON fixture that
 * `test/CommitmentVector.t.sol` reads and independently recomputes in Solidity (deploying
 * a real Tender, committing with this exact commitment, and revealing with this exact
 * price/salt) -- a mismatch here would let a bidder's own tool produce a commitment their
 * real on-chain reveal can never open, costing them their deposit.
 *
 * The fixture is checked into the repo (not regenerated by `forge test`) so `forge test`
 * never depends on Node being installed. Re-run `npm run gen:vector` and `forge test`
 * after changing anything about the commitment formula to reconfirm agreement.
 */
function main(): void {
  const chainId = 31337n;
  const tender = dummyAddress("tenderseal-cross-language-vector-tender");
  const bidder = dummyAddress("tenderseal-cross-language-vector-bidder");
  const price = 123456789n;
  const docHash = keccak256(toHex("tenderseal-cross-language-vector-doc"));
  const salt = keccak256(toHex("tenderseal-cross-language-vector-salt")) as Hex;

  const commitment = computeCommitment({ chainId, tender, bidder, price, docHash, salt });

  const vector = {
    description:
      "Cross-language test vector (Step 9a item 1): computeCommitment() in TS must equal keccak256(abi.encode(...)) in Solidity for these exact inputs.",
    chainId: chainId.toString(),
    tender,
    bidder,
    price: price.toString(),
    docHash,
    salt,
    commitment,
  };

  const outPath = join(__dirname, "..", "fixtures", "commitment-vector.json");
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, JSON.stringify(vector, null, 2) + "\n");

  console.log(`Wrote cross-language commitment vector to ${outPath}`);
  console.log(`  commitment: ${commitment}`);
}

main();
